apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mediawiki
spec:
  destination:
    name: ''
    namespace: mediawiki
    server: 'https://kubernetes.default.svc'
  source:
    path: manifests
    repoURL: 'https://github.com/rahul-subash/mediawiki-k8s-deployment.git'
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: []