apiVersion: v1
kind: Secret
metadata:
  name: mediawiki-azure-secret
type: Opaque
data:
  azurestorageaccountname: <base64_azurestorageaccountname>
  azurestorageaccountkey: <base64_azurestorageaccountkey>
---
apiVersion: v1
kind: PersistentVolume
metadata:
 name: mediawiki-fileserver
spec:
 capacity:
   storage: 3Gi
 accessModes:
 - ReadWriteOnce
 persistentVolumeReclaimPolicy: Retain
 storageClassName: azurefile
 azureFile:
   secretName: mediawiki-azure-secret
   shareName: <file_share_name>
   readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: mediawiki-fileserver-claim
spec:
 accessModes:
 - ReadWriteOnce
 storageClassName: azurefile
 volumeName: mediawiki-fileserver
 resources:
   requests:
     storage: 3Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
 name: mariadb-fileserver
spec:
 capacity:
   storage: 3Gi
 accessModes:
 - ReadWriteOnce
 persistentVolumeReclaimPolicy: Retain
 storageClassName: azurefile
 azureFile:
   secretName: mediawiki-azure-secret
   shareName: <file_share_name>
   readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: mariadb-fileserver-claim
spec:
 accessModes:
 - ReadWriteOnce
 storageClassName: azurefile
 volumeName: mariadb-fileserver
 resources:
   requests:
     storage: 3Gi
